### ISSUE TITLE
Error installing babel

### ISSUE THREAD

**Issue by thond1st** [MitocGroup/deep-framework#294] opened 2016-03-25 15:04 UTC
I'm in a new ArchLinux install in VirtualBox. Still no luck with Win10.

Had some trouble installing deepify with '-g' flag with and without sudo.
What worked is switching to root user.
but
Running
$ deepify helloworld ~/deep-hello-world
produces the error below.

Error installing "babel@^5.x.x" globally: Error: Command 'npm list -g --depth 0 "babel@^5.x.x"   > /dev/null 2>&1 ||  npm install -g "babel@^5.x.x"  > /dev/null 2>&1' failed in '/media/sf_D_DRIVE/portables/projects/javascript/nodejs/deep-framework/deep-hello-world' with error: Error: Command failed: npm list -g --depth 0 "babel@^5.x.x"   > /dev/null 2>&1 ||  npm install -g "babel@^5.x.x"  > /dev/null 2>&1
 
14:45:36 GMT+0000 (UTC)  Error while installing babel: Error: Command 'npm list -g --depth 0 "babel@^5.x.x"   > /dev/null 2>&1 ||  npm install -g "babel@^5.x.x"  > /dev/null 2>&1' failed in '/media/sf_D_DRIVE/portables/projects/javascript/nodejs/deep-framework/deep-hello-world' with error: Error: Command failed: npm list -g --depth 0 "babel@^5.x.x"   > /dev/null 2>&1 ||  npm install -g "babel@^5.x.x"  > /dev/null 2>&1
 
14:45:36 GMT+0000 (UTC)  [Error: Command '/usr/bin/node /usr/bin/deepify install github://MitocGroup/deep-microservices-helloworld --init' failed in '/media/sf_D_DRIVE/portables/projects/javascript/nodejs/deep-framework/deep-hello-world' with exit code 1]

**Comment by thond1st** [comment] 2016-03-25 15:19
It seems to run even though with the errors above. It opened the page on my browser but when inputing my name and clicking the button I got an error in console.

Error: Cannot find module '/home/thond1st/deep-hello-world/deep-microservices-helloworld/Backend/src/SayHello/bootstrap.js'

Checked the directory and bootstrap.js is missing. Maybe it is due to the error on my first comment.

**Comment by eistrati** [comment] 2016-03-25 15:54
@thond1st It looks like the `deepify compile-es6` failed. Let us take a look at this issue and we'll get back to you asap.

**Comment by thond1st** [comment] 2016-03-25 16:06
Thanks @eistrati

**Comment by eistrati** [comment] 2016-03-25 16:07
You should be able to install deepify globally. We think the root cause is in permissions for global node modules. Can you please take a look at below article and see if it solves the problem?

http://stackoverflow.com/questions/19874582/change-default-global-installation-directory-for-node-js-modules-in-windows

**Comment by thond1st** [comment] 2016-03-25 16:15
I'll look into the link. Thanks

**Comment by AlexanderC** [comment] 2016-03-25 16:18
@thond1st as of linux installation, please make sure the user you are running commands under, have permissions to install npm modules globally. In order to test it run `npm install -g` from the same terminal window without being a sudoer (ex. `npm install -g {some_module}`).

**Comment by thond1st** [comment] 2016-03-25 17:27
@AlexanderC You are right. I haven't had the same issue with my old Arch dual boot before but my Node.js installation is old at that time installed through package manager.
I installed Node.js through NVM this time and npm install globally is working.
Deep-Hello-World is now working. in Linux VM. I'll try to figure the Win10 issue.
@eistrati and @AlexanderC  Thank you! :)

**Comment by eistrati** [comment] 2016-03-25 23:25
Glad it worked. I'll close this issue now, and feel free to reopen if you have other related issues, or open new ones ;)

**Closed by eistrati** 2016-03-25 23:25 UTC
